service: tank-ws-server

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    TABLE_NAME: !Ref ConnectionsTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
          Resource:
            - !GetAtt ConnectionsTable.Arn
            - !Sub "${ConnectionsTable.Arn}/index/*"
        - Effect: Allow
          Action: execute-api:ManageConnections
          Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*"

functions:
  websocket:
    handler: handler.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-connections
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: room
            AttributeType: S
          - AttributeName: role
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: RoomRoleIndex
            KeySchema:
              - AttributeName: room
                KeyType: HASH
              - AttributeName: role
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true